services:
  realtime-stt-server:
    build:
      context: .
      target: ${WHISPER_OVERLAY_DOCKER_TARGET:-gpu}
    image: realtime-stt-server
    container_name: realtime-stt-server
    command: ${WHISPER_OVERLAY_SERVER_COMMAND:-python3 realtime-stt-server.py --host 0.0.0.0}
    volumes:
      - cache:/root/.cache
    ports:
      - "7007:7007"

    # if 'gpu' target
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

volumes:
  cache:
